from title.physical_text import ph_sp_1
from title.physical_text import ph_t_1
from title.physical_text import ph_t_2
from title.physical_text import ph_t_3
from title.physical_text import ph_t_4
from title.physical_text import ph_t_5
from title.physical_text import ph_t_6
from title.physical_text import ph_t_7
from title.physical_text import ph_t_8
from title.physical_text import ph_t_9
from title.physical_text import ph_t_10